CREATE TABLE DEPARTAMENTO (
    ID NUMBER(10,0) GENERATED ALWAYS AS IDENTITY,
    NOMBRE VARCHAR(50) NOT NULL,
    PORCENTAJE DECIMAL(5,2) NOT NULL,
    PRIMARY KEY (ID)
);

CREATE TABLE TIPO_CUBRIMIENTO (
    ID NUMBER(10,0) GENERATED ALWAYS AS IDENTITY,
    NOMBRE VARCHAR(50) NOT NULL,
    PORCENTAJE DECIMAL(5,2) NOT NULL,
    PRIMARY KEY (ID)
);

CREATE TABLE TOMADOR (
    ID NUMBER(10,0) GENERATED ALWAYS AS IDENTITY,
    CEDULA VARCHAR(20) NOT NULL,
    NOMBRE VARCHAR(50) NOT NULL,
    GENERO VARCHAR(10) CHECK (GENERO IN ('masculino', 'femenino')),
    EDAD INT CHECK (EDAD BETWEEN 18 AND 100),
    IDDEPARTAMENTO NUMBER(10,0),
    PRIMARY KEY (ID),
    FOREIGN KEY (IDDEPARTAMENTO) REFERENCES DEPARTAMENTO(ID)
);

CREATE TABLE POLIZA (
    ID NUMBER(10,0) GENERATED ALWAYS AS IDENTITY,
    numero VARCHAR(20) NOT NULL,
    valorasegurable DECIMAL(10,2) DEFAULT 0,
    ID_TIP NUMBER(10,0),
    TOM_ID NUMBER(10,0),
    fechainicio DATE,
    fechafin DATE,
    PRIMARY KEY (ID),
    FOREIGN KEY (ID_TIP) REFERENCES TIPO_CUBRIMIENTO(ID),
    FOREIGN KEY (TOM_ID) REFERENCES TOMADOR(ID)
);