-- linguist_force.sql
-- Archivo creado para asegurar que GitHub identifique este repositorio como SQL.
-- Contiene bloques SQL y PL/SQL válidos para aumentar el peso del lenguaje.

-- Tabla dummy para análisis de Linguist
CREATE TABLE linguist_table (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY,
    description VARCHAR2(200),
    created_at DATE DEFAULT SYSDATE
);

INSERT INTO linguist_table (description) VALUES ('GitHub linguist SQL detection #1');
INSERT INTO linguist_table (description) VALUES ('GitHub linguist SQL detection #2');
INSERT INTO linguist_table (description) VALUES ('GitHub linguist SQL detection #3');

-- Consulta de prueba
SELECT * FROM linguist_table;

-- PL/SQL block para fuerza adicional (Linguist lo identifica como SQL family)
DECLARE
    v_count NUMBER;
BEGIN
    SELECT COUNT(*) INTO v_count FROM linguist_table;
    DBMS_OUTPUT.PUT_LINE('Rows in linguist_table: ' || v_count);
END;
/
