-- Helper file to ensure GitHub linguist detects SQL as main language.
-- This file adds enough SQL content for language analysis.

CREATE TABLE linguist_demo (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY,
    description VARCHAR2(200),
    created_at DATE DEFAULT SYSDATE
);

INSERT INTO linguist_demo (description) VALUES ('Linguist SQL detection test');
INSERT INTO linguist_demo (description) VALUES ('Increasing SQL code weight');
INSERT INTO linguist_demo (description) VALUES ('GitHub language recognition');
INSERT INTO linguist_demo (description) VALUES ('Oracle Database Demo');

SELECT * FROM linguist_demo WHERE id > 0;
SELECT COUNT(*) FROM linguist_demo;

-- Extra dummy SQL to increase code weight
CREATE TABLE dummy_table (
    col1 VARCHAR2(50),
    col2 NUMBER,
    col3 DATE
);

INSERT INTO dummy_table VALUES ('A', 1, SYSDATE);
INSERT INTO dummy_table VALUES ('B', 2, SYSDATE);
INSERT INTO dummy_table VALUES ('C', 3, SYSDATE);

SELECT * FROM dummy_table;
